### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined when field is undefined 

### ISSUE THREAD

**Issue by neozhu** [devWaleed/JQuery-JSON-Form-Binding#3]
![image](https://user-images.githubusercontent.com/1549611/110238527-13842900-7f7d-11eb-9a7f-fbdbb4ce4579.png)
![image](https://user-images.githubusercontent.com/1549611/110238540-1ed75480-7f7d-11eb-96be-e11706b8456e.png)
when field is undefined ;
![image](https://user-images.githubusercontent.com/1549611/110238642-c94f7780-7f7d-11eb-9ff0-ac42031c74f1.png)

**Comment by devWaleed** [comment]
@neozhu Hey, I have updated the code. Please take latest code and try again.

**Comment by neozhu** [comment]
It's ok.
